### ISSUE TITLE
Change named template to key-array?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#103]
If they can be loaded from separate files, etc, names need to be unique, so may as well enforce this.

Also, the model becomes more consistent.

```yaml
author-apa-long:
  - contributor: author
    format: long
```
