### ISSUE TITLE
Disambiguate the `format` property

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#116]
Currently using this both to signal data-type specific formatting, and also child templates.

Should probably change the latter to "children".

Also, for type-safety (to limit confusing compiler errors), I'm not thrilled with this:

https://github.com/bdarcus/csl-next/blob/8b6f331fa0de2f86fac8b36f3b39a5571eb991f5/src/style.ts#L564

Make dedicated properties each; maybe:

```yaml
bibliography:
  templates:
    - delimiter: space
      templates:
      - templateKey: author-apa-full
      - date: issued
        format: year
        wrap: parentheses
      - templateKey: title
      - templateKey: container-apa
      - templateKey: howpublished-apa
  ```
