### ISSUE TITLE
Add substitution

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#122]
This is the default config, and by far the most common configuration we see in existing 1.0 styles:

```yaml
  substitute:
    author:
      - editor
      - translator
      - title # this still needs work; it assumes no formatting
  ```

https://github.com/bdarcus/csl-next/blob/e0965d82bcccbc8babb5157cd5d6c4d8987663f8/src/style/options.ts#L19

It should be straightforward enough: modify `formatContributors` to do the substitution, and then keep track of having substituted (in the `ProcHints`?).
