### ISSUE TITLE
Rely more on parameters, less on conditional?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#13]
The `TemplateModel` and `Cond` structure is now pretty flexible, but potentially a bit confusing.

Here's what I think is a mostly correct way to handle configuring default and narrative citations.

```yaml
citation:
  format:
    - when:
        - mode: narrative
          format:
            - groupBy: cs-author
              template: author-apa
              delimiter: ", "
              andAs: symbol
              format:
                - groupBy: cs-year
                  prefix: (
                  suffix: )
                  format:
                    - variable: issued
      else:
        - groupBy: cs-author-year # not sure this grouping is right
          prefix: (
          suffix: )
          delimiter: "; "
          format:
            - template: author-apa
            - variable: issued
```

Maybe we could define two kinds of conditions somehow, so maybe could do something like the below?

Only makes sense if we can clearly distinguish `locale` and `mode` from the other kinds of conditions? Maybe, in effect, both are kinds of modes?

```yaml
---
citation:
  - modes:
      locale: es
      citation: narrative
    groupBy: cs-author
    delimiter: ", "
    andAs: symbol
    format:
      - template: author-apa
        suffix: " "
        format:
          - groupBy: cs-year
            prefix: (
            suffix: )
            variable: issued
```

In that model, there would be `modes` and `conditions`.

Does that distinction make sense though?

But then ... 

if _that_ makes sense, maybe can generalize that also?

```yaml
citation:
  - modes:
      locale: es
      citation: narrative
  - predicates:
      isDate: issued
      isRefType: ["book"]
      match: any
    format:
      ...
```

The advantage is it's simpler syntax.

The disadvantage is it's less flexible.

Except, maybe if it was allowed in named templates also, that disadvantage goes away?

```yaml
template:
  name: title-abc
  predicates:
    locale: es
    citation: narrative
    isDate: issued
    isRefType:
      - book
    match: all
  format: ...
```

OTOH, not sure how much it buys, or at what costs.

**Comment by denismaier** [comment]
I don't know at the moment. 

Modes vs conditionals is somewhat arbitrary. I mean there's clearly no need for both, but it makes the different levels explicit.

**Comment by denismaier** [comment]
Maybe we should study what biblatex does ... https://mirror.foobar.to/CTAN/macros/latex/contrib/biblatex-ms/doc/biblatex-ms.pdf

**Comment by bdarcus** [comment]
Hah; that's always a good suggestion!

**Comment by denismaier** [comment]
There was also an interesting suggestion here: https://github.com/citation-style-language/schema/issues/63#issuecomment-1337129810

**Comment by bdarcus** [comment]
You now biblatex better than I, but ...

On first glance, it looks like it has some flat parameters to handle this. First example I found is this, with a default value of a comma:

```tex
\textcitedelim 
```

IUC, that is another approach, but would yield a potentially large number of parameter properties.

Or maybe can do something like:

```yaml
citation:
  type: intext
  prefix: ( # default for intext?
  suffix: )
  andAs: symbol # default parameter for citation
  groupBy: cs-author-year # default
  modes: 
    - narrative:
        affixLevel: inner # mode-specific parameters, though this would be default for this mode
        andAs: term # to support the APA distinction
  format:
    - template: author-apa
      suffix: ", "
    - variable: issued
    - template: locators-apa
      prefix: ": "
  ...
```

Some less flexibility there, and slightly harder to code, but maybe easier for authors.

Not sure how I'd add locale here. Maybe a `when` conditional inside `format`? But that returns to this question I asked:

https://github.com/citation-style-language/schema/issues/63#issuecomment-645338761

I still don't understand the answer.

I guess the CSL-M way would be:

```yaml
formats:
  - locale: de
    template: author-apa-de
  - template: author-apa
```

-----------------------------

> There was also an interesting suggestion here ...

I don't follow that comment; the "per-item" example. What might the implication be here?

----------------

PS - not even thought about this sort of example!

https://ctan.math.illinois.edu/macros/latex/contrib/mcite/mcite.pdf

**Comment by bdarcus** [comment]
Maybe multilingual requires both the locale conditional AND a property
within it to say what localized terms to use?

So to go to that comment you cited, maybe it's just a `localization` property on the main object (like `bibliography`, or even the style?), with one value being "per-item"?

**Comment by bdarcus** [comment]
I think I understand that comment now.

See #14

**Comment by bdarcus** [comment]
Just playing a bit, here's a possible "flatter" model, somewhat like biblatex, where details of mode are configured in parameters.

This is a bit of a fork-in-the-road in terms of this experiment. WDYT @denismaier: should I just go with this?

The obvious advantages of something like this that I see:

1. simpler syntax easier to author (so simple, in fact, it's well suited to a string template language)
2. potentially more concise styles
3. easier to extend going forward; adding parameters shouldn't break things
4. can borrow ideas and such for those parameters from biblatex, which I've always said is well-designed (and tested), even if they have somewhat different design priorities
5. can still include the conditional for certain cases (but if templates can be shared across styles would likely be less needed)

My justification for putting `narrative` there is that it's just another context.

- Style
  - citation
    - narrative 
  - bibliography

Could add an explicit `modes` property there.

```yaml
---
# this is a flatter model, relying more heavily on parameters
citation:
  # in CSL 1.0, we have this global, but it's specific to citations
  intext: true
  # There's only so many ways to sort and group, so let's just itemize them
  sort: cs-author-year
  group: cs-author-year
  # again: another example where there are only a few options
  affixes: parentheses # maybe would need localizing though?
  # andAs is a property of lists, in this case the citation
  andAs: term
  delimiter: semi-colon
  narrative:
    # maybe a little dicey, but to keep format simpler
    affixLevel: year
    # here we override andAs for this mode
    andAs: symbol
    delimiter: comma
  format:
    # in this example, no need for conditional here
    # configure delimiters in parameters
    # author-date styles are such a hassle at this level!
    - template: author-apa
    - template: year
    - template: locators-apa
  ```

As for `mcite`, that's easy, I think:

```yaml
bibliography:
  groupBy: cs-as-cited
```
