### ISSUE TITLE
chore: add CI

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#20]
Adapted some ideas from [node-ts-starter-cli](https://github.com/FreekMencke/node-ts-starter-cli).

-------------

PS - been experimenting with [lefthook](https://github.com/evilmartians/lefthook) for commit hooks. This matches the CI, and formats staged files:

```yaml
# lefthook.yml
# lefthook add pre-commit

pre-commit:
  commands:
    format:
      glob: "*.ts"
      run: npx rome format --write {staged_files}
```
