### ISSUE TITLE
Make grouping parameter available globally

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#22]
Not really sure why it should be restricted to the citation or bibliography contexts?

Now I'm wondering if it all needs a bit of restructuring; say:

```yaml
title: Foo
options:
  grouping:
templates:
citation:
  options:
  contexts:
    options:
  templates:
```

So consistent distinction between `options` and `templates`, available at all levels, where lower-levels override higher levels?

Or maybe the current distinction between `templates` (available only globally, and in external files) and `formats` (available only at lower levels), makes sense?

Or to go back to the "flatter" idea, maybe `options` is only available at the top-level, and lower-level parameters are also configured there? It's easier to program, I'd think.
