### ISSUE TITLE
Sort too limited

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#25]
Probably need to revert back to the CSL 1.0 design for this:

```yaml
sort:
  - key: author
    order: ascending
  - key: year
    order: descending
```
