### ISSUE TITLE
Confirm delimiter is available in the right places

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#36]
Something seems a bit off ATM. 

Need to be able to do stuff like [this](https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L635).

This currently is valid:

```yaml
      - when:
          - hasVariable:
              - issued
              # - accessed
            match: any
            format:
              - delimiter: " "
                format:
                  - template: one
                  - template: two
```

... but this is not (and so is a bug):

```yaml
       else:
         format:
           - delimiter: ", "
             format:
               - template: one
               - template: two
```

EDIT: I think that outer `format` isn't allowed there, because unnecessary.

But we shouldn't require duplication to change a delimiter. 

I think, however, we need to allow and encourage the below (and _maybe_ somehow also move that to a parameter)?

```yaml
- delimiter: " "
  format: one
```

cc @adam3smith  - here's an answer to one of your questions, though there's an inconsistency I need to fix.
