### ISSUE TITLE
Add term and text/str to `TemplateModel`

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#45]
At first thought, I think something like this is the right approach:

```yaml
- term: available
  emph: true
- text: foo bar
```

-------------

Looking at the style repo, it seems this is overwhelming used for localized prefixes, in particular, for content.

That also requires using `cs:group` and such.

So maybe instead could do:

```yaml
- template: container-apa
  prefixTerm: in
``` 

Or maybe:

```yaml
- template: container-apa
  prefix:
    term: in
    emph: true
```
